/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

group = "com.jeff_media"
version = "1.0-SNAPSHOT"
description = "JeffBot"
java.sourceCompatibility = JavaVersion.VERSION_17

plugins {
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.freefair.lombok") version "6.6.1"
    `maven-publish`
    `java-library`
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("net.dv8tion:JDA:5.0.0-beta.2")
    api("ch.qos.logback:logback-classic:1.2.11")
    api("org.yaml:snakeyaml:1.33")
    compileOnly("org.jetbrains:annotations:16.0.2")
}

application {
    mainClass.set("com.jeff_media.jeffbot.Main")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
